# Generated by Django 4.2.11 on 2024-10-16 19:05

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
                ('edu_photo', models.ImageField(blank=True, null=True, upload_to='markaz/', verbose_name='Markaz Rasmi 1 dona')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Markaz telefon raqami')),
                ('telegram_admin', models.URLField(blank=True, max_length=111, null=True, verbose_name='Telegram Admin')),
                ('telegram_chanel', models.URLField(blank=True, max_length=111, null=True, verbose_name='Telegram Kanal')),
                ('instagram', models.URLField(blank=True, max_length=111, null=True, verbose_name='Instagram')),
                ('you_tube', models.URLField(blank=True, max_length=111, null=True)),
                ('email', models.CharField(blank=True, max_length=111, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=111, verbose_name='Kurs Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.FloatField(default=41.3112, max_length=111, verbose_name='Lokatsiya Latidude')),
                ('location_longitude', models.FloatField(default=69.2797, max_length=111, verbose_name='Lokatsiya Longitude')),
                ('location_text', models.TextField(blank=True, null=True, verbose_name='Lokatsiya Matni')),
                ('location_video', models.FileField(blank=True, null=True, upload_to='location/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm'])], verbose_name='Lokatsiya Videosi')),
            ],
        ),
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, default='new_user', max_length=111, null=True, verbose_name='Foydalanuvchi Ismi')),
                ('user_phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Foydalanuvchi Telefon Raqami')),
                ('user_phone_number2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Foydalanuvchi Aloqa raqami')),
                ('course_name', models.CharField(blank=True, max_length=111, verbose_name='Kurslar')),
                ('course_type', models.CharField(blank=True, max_length=33, null=True, verbose_name='Kurs Turi')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_video', models.CharField(blank=True, null=True, verbose_name="Kurs Videosi ID'si")),
                ('course_text', models.TextField(blank=True, null=True, verbose_name='Kurs Matni')),
                ('course_photo', models.ImageField(blank=True, null=True, upload_to='kurslar/', verbose_name='Kurs Rasmi')),
                ('course_pdf', models.FileField(blank=True, null=True, upload_to='kurslar/', verbose_name='Kurs PDF Fayl')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course')),
            ],
        ),
        migrations.CreateModel(
            name='About_Edu_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='markaz/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])], verbose_name='Markaz videosi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='markaz/', verbose_name='Markaz rasmi')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='markaz/', verbose_name='Markaz pdf')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.about_edu')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='new_user', max_length=111, null=True, verbose_name='F.I.SH')),
                ('username', models.CharField(blank=True, max_length=111, null=True, unique=True, verbose_name='Telegram username')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon raqami')),
                ('phone_number2', models.CharField(blank=True, max_length=50, null=True, verbose_name="Qo'shimcha Telefon raqami")),
                ('activity', models.CharField(blank=True, max_length=33, null=True, verbose_name='Faoliyat turi')),
                ('telegram_id', models.BigIntegerField(blank=True, default=1, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=33, null=True, verbose_name='Tanlangan til')),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('password', models.CharField(max_length=111, null=True)),
                ('is_superuser', models.BooleanField(default=False, null=True)),
                ('first_name', models.CharField(default='new_user', max_length=111, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(default='new_user', max_length=111, null=True, verbose_name='Familya')),
                ('email', models.CharField(default='new_user@gmail.com', max_length=111, null=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
