# Generated by Django 4.2.11 on 2024-10-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_course',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
