from . import start
from . import help
from . import language
from . import update_db
from . import admin
from . import anketa
from . import main_menu
from . import kurslar
from . import register_course
from . import about_education
from . import echo
